---
- name: install redhat dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ redhat_package_dependencies }}"
  when: ansible_distribution == "RedHat"

- name: install centos dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ centos_package_dependencies }}"
  when: ansible_distribution == "CentOS"

- name: install redhat ceph-common
  package:
    name: "ceph-common"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"

- name: install redhat ceph-mon package
  package:
    name: "ceph-mon"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mon_group_name in group_names

- name: install redhat ceph-osd package
  package:
    name: "ceph-osd"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - osd_group_name in group_names

- name: install redhat ceph-mds package
  package:
    name: "ceph-mds"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mds_group_name in group_names

- name: install redhat ceph-fuse package
  package:
    name: "ceph-fuse"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names

- name: install redhat ceph-base package
  package:
  package:
    name: "ceph-base"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - client_group_name in group_names

- name: install redhat ceph-test package
  package:
    name: ceph-test
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when: ceph_test

- name: install redhat ceph-radosgw package
  package:
    name: ceph-radosgw
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when: rgw_group_name in group_names

- name: install redhat nfs-ganesha-ceph package
  package:
    name: nfs-ganesha-ceph
  when:
    - nfs_group_name in group_names
    - nfs_file_gw

- name: install redhat nfs-ganesha-rgw and ceph-radosgw packages for rhcs 2
  package:
    name: "{{ item }}"
  with_items:
    - nfs-ganesha-fsal
    - ceph-radosgw
  when:
    - nfs_group_name in group_names
    - nfs_obj_gw
    - ceph_rhcs_version == "2"

- name: install nfs cephfs gateway
  package:
    name: nfs-ganesha-ceph
  when:
    - nfs_group_name in group_names
    - nfs_file_gw
    - ceph_rhcs_version == "3"

- name: install redhat nfs-ganesha-rgw and ceph-radosgw packages for rhcs 3
  package:
    name: "{{ item }}"
  with_items:
    - nfs-ganesha-rgw
    - ceph-radosgw
  when:
    - nfs_group_name in group_names
    - nfs_obj_gw
    - ceph_rhcs_version == "3"

- name: install redhat ceph-mgr package
  package:
    name: ceph-mgr
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  when:
    - mgr_group_name in group_names
    - ceph_release_num.{{ ceph_release }} > ceph_release_num.jewel
