---
- name: fetch ceph red hat development repository
  uri:
    url: https://shaman.ceph.com/api/repos/ceph/{{ ceph_dev_branch }}/{{ ceph_dev_sha1 }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/repo
    return_content: yes
  register: ceph_dev_yum_repo

- name: configure ceph red hat development repository
  copy:
    content: "{{ ceph_dev_yum_repo.content }}"
    dest: /etc/yum.repos.d/ceph-dev.repo
    owner: root
    group: root
    backup: yes

- name: fetch nfs-ganesha red hat development repository
  uri:
    url: https://shaman.ceph.com/api/repos/nfs-ganesha/next/latest/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/flavors/{{ nfs_ganesha_flavor }}/repo
    return_content: yes
  register: nfs_ganesha_dev_yum_repo
  when:
    - nfs_ganesha_dev is defined
    - nfs_ganesha_dev

- name: add nfs-ganesha development repository
  copy:
    content: "{{ nfs_ganesha_dev_yum_repo.content }}"
    dest: /etc/yum.repos.d/nfs-ganesha-dev.repo
    owner: root
    group: root
    backup: yes
  when:
    - nfs_ganesha_dev is defined
    - nfs_ganesha_dev

