---
- include: check_mandatory_vars.yml

- include: pre_requisite.yml
  when: not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ceph_disk_cli_options_facts.yml

- include: check_devices.yml

- name: generate device list when osd_auto_discovery
  set_fact:
    devices: "{{ devices | default([]) + [ item.key | regex_replace('^', '/dev/') ] }}"
  with_dict: "{{ ansible_devices }}"
  when:
    - ansible_devices is defined
    - item.value.removable == "0"
    - item.value.partitions|count == 0
    - item.value.holders|count == 0
    - osd_auto_discovery

- include: ./scenarios/collocated.yml
  when:
    - osd_scenario == 'collocated'
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./scenarios/non-collocated.yml
  when:
    - osd_scenario == 'non-collocated'
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: create lvm osds with ceph-volume
  include: ./scenarios/lvm.yml
  when:
    - osd_scenario == 'lvm'
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- name: ensure osd daemons are started
  include: start_osds.yml
  when:
    - not containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False

- include: ./docker/main.yml
  when: containerized_deployment
  # Hard code this so we will skip the entire file instead of individual tasks (Default isn't Consistent)
  static: False
