---
# Copy Ceph configs to host
- include: copy_configs.yml
# Copy Ganesha Ceph configs to host
- include: copy_ganesha_configs.yml
  when: not mon_containerized_deployment_with_kv

- include: start_docker_nfs.yml

