---
##########
# DOCKER #
##########

ceph_mgr_docker_extra_env:
ceph_config_keys: [] # DON'T TOUCH ME


###########
# SYSTEMD #
###########
# ceph_mgr_systemd_overrides will override the systemd settings
# for the ceph-mgr services.
# For example,to set "PrivateDevices=false" you can specify:
#ceph_mgr_systemd_overrides:
#  Service:
#    PrivateDevices: False
